# Generated by Django 3.1.14 on 2022-04-03 20:12

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_MS', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=255)),
                ('Date_pub_MS', models.DateField()),
                ('Fichier_MS', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_send', models.CharField(max_length=50)),
                ('User_received', models.CharField(max_length=50)),
                ('Date_send_msg', models.DateTimeField()),
                ('Content_msg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Contenu', models.CharField(max_length=255)),
                ('Date_pub', models.DateField()),
                ('Type', models.CharField(max_length=5)),
                ('Fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_Ressource', models.CharField(max_length=50)),
                ('Description_Ressource', models.CharField(max_length=255)),
                ('Fichier_Ressource', models.FileField(upload_to='')),
                ('Image_Ressource', models.ImageField(upload_to='')),
                ('Date_pub_ressource', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Complet', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, null=sqlalchemy.sql.expression.false)),
                ('Adresse', models.CharField(max_length=150)),
                ('Profession', models.CharField(max_length=60)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
