# Generated by Django 3.1.14 on 2022-04-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Date_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
