# Generated by Django 3.1.14 on 2022-04-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20220408_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Fichier',
            field=models.FileField(upload_to='Images/'),
        ),
    ]
