# Generated by Django 3.1.14 on 2022-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_auto_20220409_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
