# Generated by Django 3.1.14 on 2022-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_auto_20220409_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressources',
            name='Image_Ressource',
        ),
        migrations.AlterField(
            model_name='message',
            name='Date_send_msg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='Date_pub_ressource',
            field=models.DateField(auto_now=True),
        ),
    ]
