# Generated by Django 3.1.14 on 2022-04-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0009_auto_20220410_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressources',
            old_name='Date_pub_ressource',
            new_name='Date_pub_Ressource',
        ),
    ]
