# Generated by Django 3.1.14 on 2022-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_auto_20220410_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressources',
            name='Date_pub_Ressource',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
