# Generated by Django 3.1.14 on 2022-04-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0011_auto_20220410_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ressources',
        ),
    ]
