# Generated by Django 3.1.14 on 2022-04-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0012_delete_ressources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_Ressource', models.CharField(max_length=50)),
                ('Description_Ressource', models.CharField(max_length=255)),
                ('Fichier_Ressource', models.FileField(upload_to='')),
                ('Date_pub_Ressource', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
