# Generated by Django 3.1.14 on 2022-04-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0013_ressources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage_stress',
            old_name='Description',
            new_name='Description_MS',
        ),
        migrations.AlterField(
            model_name='manage_stress',
            name='Date_pub_MS',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
