# Generated by Django 3.1.14 on 2022-04-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0014_auto_20220411_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manage_Stress',
        ),
    ]
