# Generated by Django 3.1.14 on 2022-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0015_delete_manage_stress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_MS', models.CharField(max_length=50)),
                ('Description_MS', models.CharField(max_length=255)),
                ('Date_pub_MS', models.DateTimeField(auto_now=True)),
                ('Fichier_MS', models.FileField(upload_to='')),
            ],
        ),
    ]
