# Generated by Django 3.1.14 on 2022-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0016_manage_stress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Fichier',
            field=models.FileField(upload_to='fichier_NP/'),
        ),
    ]
