# Generated by Django 3.1.14 on 2022-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0017_auto_20220411_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Fichier',
            field=models.ImageField(upload_to='fichier_NP/'),
        ),
    ]
