# Generated by Django 3.1.14 on 2022-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0018_auto_20220425_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Fichier',
            field=models.ImageField(upload_to=''),
        ),
    ]
