# Generated by Django 3.1.14 on 2022-05-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0019_auto_20220426_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auteur', models.CharField(max_length=150)),
                ('Commentaire', models.CharField(max_length=255)),
                ('Date_pub_com', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
