# Generated by Django 3.1.14 on 2022-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0020_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Auteur',
        ),
    ]
