# Generated by Django 3.1.14 on 2022-05-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0021_remove_comments_auteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
