# Generated by Django 3.1.14 on 2022-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0022_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commentaire', models.CharField(max_length=255)),
                ('Date_pub_com', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
