# Generated by Django 3.1.14 on 2022-05-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0024_auto_20220520_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Titre_pub',
        ),
    ]
