# Generated by Django 4.0.4 on 2022-05-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0026_remove_comments_com_pub_remove_user_adresse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
