# Generated by Django 4.0.4 on 2022-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0027_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commentaire', models.TextField(max_length=255, null=True)),
                ('Date_pub_com', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
