# Generated by Django 4.0.4 on 2022-05-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0028_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Commentaires',
        ),
        migrations.RenameField(
            model_name='commentaires',
            old_name='Commentaire',
            new_name='Comment',
        ),
    ]
