# Generated by Django 4.0.4 on 2022-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0030_delete_commentaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Age', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Departement', models.CharField(max_length=50)),
                ('Profession', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
