# Generated by Django 4.0.4 on 2022-05-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0031_utilisateur_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='Image_profil',
            field=models.ImageField(default='/static/img/default-avatar.jpg', upload_to=''),
        ),
    ]
