# Generated by Django 4.0.4 on 2022-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0032_utilisateur_image_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Image_profil',
            field=models.ImageField(upload_to=''),
        ),
    ]
