# Generated by Django 4.0.4 on 2022-05-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0033_alter_utilisateur_image_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='Auteur_pub',
            field=models.CharField(default='Utilisateur', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='Contenu',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
