# Generated by Django 4.0.4 on 2022-05-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0034_news_post_auteur_pub_alter_news_post_contenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_pub', models.CharField(max_length=150)),
                ('Auteur_Comment_pub', models.CharField(max_length=50)),
                ('Comment_pub', models.TextField(max_length=255)),
                ('Date_Comment_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='manage_stress',
            name='Description_MS',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='Description_Ressource',
            field=models.TextField(max_length=255),
        ),
    ]
