# Generated by Django 4.0.4 on 2022-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0035_commentaires_alter_manage_stress_description_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Auteur_pub',
            field=models.CharField(max_length=50),
        ),
    ]
