# Generated by Django 4.0.4 on 2022-05-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0036_alter_news_post_auteur_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='Auteur_Comment_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
        ),
    ]
