# Generated by Django 4.0.4 on 2022-05-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0037_alter_commentaires_auteur_comment_pub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaires',
        ),
    ]
