# Generated by Django 4.0.4 on 2022-05-31 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0038_delete_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Auteur_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_pub', models.CharField(max_length=150)),
                ('Comment_pub', models.TextField(max_length=255)),
                ('Date_Comment_pub', models.DateTimeField(auto_now=True)),
                ('Auteur_Comment_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur')),
            ],
        ),
    ]
