# Generated by Django 4.0.4 on 2022-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0039_alter_news_post_auteur_pub_commentaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='Prenom',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Nom_Complet',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
