# Generated by Django 4.0.4 on 2022-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0040_remove_utilisateur_nom_remove_utilisateur_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='Auteur_Comment_pub',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='Auteur_pub',
            field=models.CharField(max_length=150),
        ),
    ]
