# Generated by Django 4.0.4 on 2022-06-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0041_alter_commentaires_auteur_comment_pub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='Auteur_Comment_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
        ),
    ]
