# Generated by Django 4.0.4 on 2022-06-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0042_alter_commentaires_auteur_comment_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='Auteur_Comment_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Webapp.utilisateur'),
        ),
    ]
