# Generated by Django 4.0.4 on 2022-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0044_commentaires_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='Likes',
            field=models.ManyToManyField(blank=True, to='Webapp.utilisateur'),
        ),
    ]
