# Generated by Django 4.0.4 on 2022-06-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0045_news_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='Likes',
        ),
        migrations.AlterField(
            model_name='news_post',
            name='Auteur_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
        ),
    ]
