# Generated by Django 4.0.4 on 2022-06-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0046_remove_news_post_likes_alter_news_post_auteur_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='User_received',
        ),
        migrations.RemoveField(
            model_name='message',
            name='User_send',
        ),
        migrations.AddField(
            model_name='message',
            name='Object_msg',
            field=models.CharField(default='Prise de Contact', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='User_send_msg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Content_msg',
            field=models.TextField(max_length=255),
        ),
    ]
