# Generated by Django 4.0.4 on 2022-06-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0047_remove_message_user_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Assistance', models.CharField(max_length=150)),
                ('Cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.message')),
                ('Suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur')),
            ],
        ),
    ]
