# Generated by Django 4.0.4 on 2022-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0048_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='Status_Assistance',
            field=models.CharField(default='Non Pris en Charge', max_length=150),
        ),
    ]
