# Generated by Django 4.0.4 on 2022-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0050_alter_assistance_status_assistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='Status_Assistance',
        ),
        migrations.AddField(
            model_name='message',
            name='Status_Assistance',
            field=models.CharField(default='Pris en Charge', max_length=150),
        ),
    ]
