# Generated by Django 4.0.4 on 2022-06-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0052_remove_message_status_assistance_message_status_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Status_msg',
            field=models.CharField(max_length=150),
        ),
    ]
