# Generated by Django 4.0.4 on 2022-06-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0054_remove_assistance_cas_message_psy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Psy',
        ),
    ]
