# Generated by Django 4.0.4 on 2022-06-11 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0055_remove_message_psy'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='Cas',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Webapp.message'),
            preserve_default=False,
        ),
    ]
