# Generated by Django 4.0.4 on 2022-06-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0056_assistance_cas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='news_post',
            name='Likes',
            field=models.ManyToManyField(to='Webapp.reagir'),
        ),
    ]
