# Generated by Django 4.0.4 on 2022-06-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0057_reagir_news_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Reagir',
        ),
    ]
