# Generated by Django 4.0.4 on 2022-06-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0061_remove_like_post_reacteur_like_post_reacteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_post',
            name='Reacteur',
        ),
        migrations.AddField(
            model_name='like_post',
            name='Reacteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Webapp.utilisateur'),
            preserve_default=False,
        ),
    ]
