# Generated by Django 4.0.4 on 2022-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0062_remove_like_post_reacteur_like_post_reacteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_post',
            name='Reacteur',
        ),
        migrations.AddField(
            model_name='like_post',
            name='Reacteur',
            field=models.ManyToManyField(to='Webapp.utilisateur'),
        ),
    ]
