# Generated by Django 4.0.4 on 2022-07-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0063_remove_like_post_reacteur_like_post_reacteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='Like',
            field=models.ManyToManyField(blank=True, default=None, related_name='Reaction_Utilisateur', to='Webapp.utilisateur'),
        ),
        migrations.DeleteModel(
            name='Like_Post',
        ),
    ]
