# Generated by Django 4.0.4 on 2022-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0064_news_post_like_delete_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Received_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='Object_msg',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
