# Generated by Django 4.0.4 on 2022-07-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0065_message_received_msg_alter_message_object_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Received_msg',
        ),
    ]
