# Generated by Django 4.0.4 on 2022-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0067_room_private_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='Room',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
